import "./globals.css";
import "./responsive.css";
import 'bootstrap/dist/css/bootstrap.min.css';
import NavBar from "./components/NavBar";
import Footer from "./components/Footer";

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang='en'>
      <body className=''>
        <NavBar />
        <main>{children}</main>
        <Footer />
      </body>
    </html>
  );
}
